name: dev

on:
  workflow_dispatch:

jobs:
  build:
    name: dev workflow, needed for workflow dispatch on feature branches
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4