name: iOS app build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get xcparse bottle from cache
        uses: actions/cache/restore@v4
        id: cache-restore-xcparse-bottle
        with:
          key: xcparse-bottle
          path: ./bottles # this must match between save and restore
      - name: Install and bottle xcparse
        if: steps.cache-restore-xcparse-bottle.outputs.cache-hit != 'true'
        run: |
            brew update
            brew install chargepoint/xcparse/xcparse --build-bottle
            brew bottle xcparse
            mkdir bottles
            mv ./*bottle*.tar.gz bottles
      - name: Save bottle to cache
        uses: actions/cache/save@v4
        if: steps.cache-restore-xcparse-bottle.outputs.cache-hit != 'true'
        id: xcparse-bottle
        with:
          key: xcparse-bottle
          path: ./bottles # this must match between save and restore
      - name: Install xcparse from bottle 
        if: steps.cache-restore-xcparse-bottle.outputs.cache-hit == 'true'
        run: |
            brew install -f ./bottles/*     
      - name: Install xcodegen
        run: |
          brew update  
          brew install xcodegen
          xcodegen help
          xcodegen generate --help
      - name: Update project with xcodegen
        run: xcodegen generate
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          echo $scheme_list
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -showBuildTimingSummary
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" -resultBundlePath TestResults.xcresult
      - uses: actions/upload-artifact@v4
        with:
          name: xcode_results
          path: TestResults.xcresult
      - name: Export screenshots
        run: |
          xcparse screenshots TestResults.xcresult Screenshots/
      - uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: Screenshots/
